In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split 
from sklearn import preprocessing
from sklearn import metrics
from sklearn.tree import export_graphviz
from IPython.display import Image  
import pydotplus
import numpy as np
from io import StringIO
import matplotlib.pyplot as plt

In [3]:
df = pd.DataFrame(columns=['Color', 'Forma', 'Tamanio','Clase'])
df = df.append({'Color': 'Rojo', 'Forma': 'Cuadrado', 'Tamanio':'Grande','Clase':'A'}, ignore_index=True)
df = df.append({'Color': 'Azul', 'Forma': 'Cuadrado', 'Tamanio':'Grande','Clase':'A'}, ignore_index=True)
df = df.append({'Color': 'Rojo', 'Forma': 'Redondo', 'Tamanio':'Pequeño','Clase':'B'}, ignore_index=True)
df = df.append({'Color': 'Verde', 'Forma': 'Cuadrado', 'Tamanio':'Pequeño','Clase':'B'}, ignore_index=True)
df = df.append({'Color': 'Rojo', 'Forma': 'Redondo', 'Tamanio':'Grande','Clase':'A'}, ignore_index=True)
df = df.append({'Color': 'Verde', 'Forma': 'Cuadrado', 'Tamanio':'Grande','Clase':'B'}, ignore_index=True)
print(df)

   Color     Forma  Tamanio Clase
0   Rojo  Cuadrado   Grande     A
1   Azul  Cuadrado   Grande     A
2   Rojo   Redondo  Pequeño     B
3  Verde  Cuadrado  Pequeño     B
4   Rojo   Redondo   Grande     A
5  Verde  Cuadrado   Grande     B


In [5]:
target_n=df.values[:,3]
print(target_n)
le = preprocessing.LabelEncoder()
df = df.apply(le.fit_transform)
df.head()


data = df.values[:,:3]
data_columns = list(df.columns.values[:3])
target=df.values[:,3]


clf = DecisionTreeClassifier(criterion="entropy", max_depth=2)
clf = clf.fit(data,target)
print(data)


[0 0 1 1 0 1]
[[1 0 0]
 [0 0 0]
 [1 1 1]
 [2 0 1]
 [1 1 0]
 [2 0 0]]


In [8]:
print(data_columns)
print(target_n)
dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True,feature_names = data_columns,class_names=target_n)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
#graph.write_png('iris.png')
Image(graph.create_png())

['Color', 'Forma', 'Tamanio']
[0 0 1 1 0 1]


TypeError: can only concatenate str (not "numpy.int64") to str